version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
